version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: clubDB
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_container
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://admin:admin@mongodb_container:27017/clubDB?authSource=clubDB
    depends_on:
      - mongodb

volumes:
  mongodb_data: